# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitops" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "f547f6a0cd59bbe880f2a5c6e502d03f5bd54cf6657a14382a9baaee6f8e7735"
      url "https://github.com/IHaveASegway/gitops/releases/download/v#{version}/gitops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b544753e9f35b176950f00ab5a9329ba60bdf3c8337322a70b6f4bb8767c329c"
      url "https://github.com/IHaveASegway/gitops/releases/download/v#{version}/gitops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e6f7300ff832ea02f83816b344a64684a049830d26f6e9181fa441540e3a5e9d"
      url "https://github.com/IHaveASegway/gitops/releases/download/v#{version}/gitops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1289288c7ff3924a9a7ac4d2d8a4f88c23c5164f9f21a739526063e1d92f9be"
      url "https://github.com/IHaveASegway/gitops/releases/download/v#{version}/gitops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitops"
  desc "Mass git operations across many repos, with a TUI and one-command org cloning"
  homepage "https://github.com/IHaveASegway/gitops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitops"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitops"]
    end
  end

  # No zap stanza required
end
