# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "Mass git operations across many repos, with a TUI and one-command org cloning"
  homepage "https://github.com/IHaveASegway/gitops"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/IHaveASegway/gitops/releases/download/v1.2.0/gitops_1.2.0_darwin_amd64.tar.gz"
      sha256 "8a57816fcd6dfaec318aba6bc44b6f82d1273c8ebca58e154845f76eeee980a5"

      define_method(:install) do
        bin.install "gitops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/IHaveASegway/gitops/releases/download/v1.2.0/gitops_1.2.0_darwin_arm64.tar.gz"
      sha256 "aba73f1eed0ecefd7d09ae924869384991bd190ef9b1e1f4d14b38a406f50ce7"

      define_method(:install) do
        bin.install "gitops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/IHaveASegway/gitops/releases/download/v1.2.0/gitops_1.2.0_linux_amd64.tar.gz"
      sha256 "4ba30072b311044b095e4b2760892f6ad45b8a461fa4c36da9b3782e7eafcca5"
      define_method(:install) do
        bin.install "gitops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/IHaveASegway/gitops/releases/download/v1.2.0/gitops_1.2.0_linux_arm64.tar.gz"
      sha256 "676d6bf13d6f563d373ce6a7090252ac53f91830290122e5e839ba8a6bda9761"
      define_method(:install) do
        bin.install "gitops"
      end
    end
  end

  test do
    system "#{bin}/gitops", "--version"
  end
end
